#!/usr/bin/env bash
# nginx web server listening on port 80
# returns a page that contains the string "Hello World!"

sudo apt-get update -y && sudo apt-get upgrade -y
sudo apt-get install -y nginx
sudo chown -R "$USER":"$USER" /var/www/
sudo chown -R "$USER":"$USER" /etc/nginx
echo "Hello World!" > /var/www/html/index.nginx-debian.html
sudo service nginx restart 
